import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#474747",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-surface-variant": "#444748",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#ffb3b2",
        "outline-variant": "#c4c7c8",
        "surface-container-low": "#f6f3f2",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#fcf8f8",
        "tertiary-container": "#e8e6e6",
        "surface-dim": "#ddd9d9",
        "on-secondary-fixed-variant": "#92001e",
        "inverse-surface": "#313030",
        "on-primary-container": "#656767",
        "error-container": "#ffdad6",
        surface: "#fcf8f8",
        "on-surface": "#1c1b1b",
        "on-primary": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-high": "#ebe7e7",
        "on-tertiary-container": "#676767",
        "on-tertiary-fixed": "#1b1c1c",
        tertiary: "#5e5e5e",
        "surface-container": "#f1edec",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        primary: "#5d5f5f",
        "on-primary-fixed-variant": "#454747",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#5d5f5f",
        outline: "#747878",
        error: "#ba1a1a",
        background: "#fcf8f8",
        "surface-variant": "#e5e2e1",
        "inverse-on-surface": "#f4f0ef",
        secondary: "#ba0029",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e4e2e2",
        "on-background": "#1c1b1b",
        "primary-container": "#e6e6e6",
        "secondary-fixed": "#ffdad8",
        "on-secondary-fixed": "#410008",
        "secondary-container": "#e90036",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "container-max": "1200px",
        unit: "4px",
        margin: "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Anybody", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Anybody", "sans-serif"],
        "display-lg": ["Anybody", "sans-serif"],
        "body-md": ["Courier Prime", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.1", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
